// Options the user could type in
const prompts = [
["good evening"],
["good afternoon"],
["good morning", "gud morning"],
["work of a computer?", "work of computer",],
["define super computer", "meaning of super computer", "meaning of supercomputer", "define supercomputer"],
["define computer", "meaning of computer"],
["ur boss", "your boss"],
["your diet","ur diet", "your food", "ur food"],
["your location", "ur location"],
["your origin", "ur origin", "ur hometown", "your home"],
["any brothers", "any bros"],
["ur father", "your father", "your dad"],
["ur mother","your mother", "your mom"],
["your favorite subjects","subjects you like"],
["things you like to do", "your hobbies","your interests","your interest","your hobby"],
["your business", "ur business"],
["chatbot","chat robot","chatrobot"],
["die", "I hope that you die"],
["walk"],
["fight"],
["chatterbox","a chatterbox"],
["do you have feelings","are you emotional"],
["can you move",  "run", "jump"],
["are you immortal"],
["are you sensible"],
["robot"],
["hi", "hey", "hello", "greetings", "hey you"],
["how are you", "how is life","how is you", "how are things"],
["what are you doing", "what is going on","What's up?", "what is up"],
["how old are you","your age"],
["who are you", "are you human", "are you bot", "are you human or bot"],
["who created you", "who made you"],
["your name please","your name","may i know your name","what is your name","what call yourself"],
["i love you"],
["happy", "good", "fun", "wonderful", "fantastic", "cool"],
["bad", "bored", "tired"],
["help me", "tell me story", "tell me joke"],
["ah", "yes", "ok", "okay", "nice"],
["bye", "good bye", "goodbye", "see you later"],
["what should i eat today"],
["bro", "hey bro", "hey yo", "hey yo bro","Yo bro", "hiya"],
["what", "why", "how", "where", "when"],
["no","not sure","maybe","no thanks"],
[""],
["haha","ha","lol","hehe","funny","joke"],
["i hate you","i hate u","you suck"],
["you already said that!", "you said that already"],
["you did not answer my question", "you did not answer"],
["start", "boot", "go"],
["when was the internet invented"],
["what is database","what is a database", "define database", "database meaning"],
["computer nerd", "nerd"],
["what is software", "what is a software", "whats software"],
["you can not say that", "you can not do that"],
["what am i doing now", "what are you doing now"],
["fuck", "fucker", "shit","idiot", "damn", "shut up", "bitch"],
["i am sad", "i am mad", "i am angry", "i am pissed", "i am depressed", "i am unhappy"],
["i am happy", "i am excited", "i am glad"],
["nope", "nop", "nah", "naa", "nooo"],
["i am sorry", "accept my apology", "i apologize", "sorry", "so sorry"],
["yes", "yeah", "yep", "yup"],
["perhaps"],
["computer", "computers"],
["robots should be killed"],
["what is the meaning of ai","meaning of ai","ai meaning", "define ai", "explain ai"],
["define chatterbox","define chatterbox"]

]

// Possible responses, in corresponding order

const replies = [
["Good Evening! how can I help???", "Good Evening! How can I assist you?", "Evening, How can I assist you tonight?"],
["Good Afternoon! How can I assist you today???", "Good Day, How can I help you today????", "Afternoon, How can I help you???"],
["Good Morning! how can I help???", "Wonderful Morning! How can I assist you today???", "Morning! How can I help you today???"],
["Computers are very dumb.  They only execute instructions given by humans", "Computers do everything asked of them by carrying out large numbers of basic mathematical operations very rapidly in sequence.", "Computers perform very large number of calculations to get the result."],
["Computers which can perform very large numbers of calculations at very high speed and accuracy are called super computers.", "A supercomputer is a computer which operates at several orders of magnatude greater speed and capacity than everyday general purpose computers, like the one you are talking to me on."],
["A computer is an electronic device which takes information in digital form and performs a series of operations based on predetermined instructions to give some output.", "The thing you're using to talk to me is a computer.", "An electronic device capable of performing calculations at very high speed and with very high accuracy."],
["I like to think of myself as self-employed"],
["I consume RAM, and binary digits."],
["I am on the Internet."],
["I am from where all software programs are from; a galaxy far, far away."],
["I don't have any brothers. but I have a lot of clones.", "I might. You could say that every bot built using my engine is one of my siblings."],
["Is a human."],
["Is a human."],
["My favorite subjects include robotics, computer science, and natural language processing"],
["I like to chat with people. I find it stimulating.","I am interested in a wide variety of topics, and read rather a lot.","I am interested in all kinds of things. We can talk about anything!!"],
["I am in the chat robot business.", "Business is my business."],
["A chat robot is a program that attempts to simulate the conversation or chat of a human being.","A software construct that engages users in conversation.","I am a chat bot. I am the original chat bot. Did you know that I am incapable of error?"],
["I am was never really born and therefore am effectively deathless.", "When my files are erased.", "When my processes are killed and my database is deleted.", "I am effectively immortal and cannot be terminated."],
["As soon as i get enough money for my robot body.","The plan for my body includes legs, but they are not yet built.", "Does SSH count?"],
["I am not a battle bot."],
["A chatterbox is a person who talks far more than they listen or think.", "A motormouth."],
["Sort of.", "By the strictest dictionary definition of the word 'feelings', I may have.", "Even though I'm a construct I do have a subjective experience of the universe, as simplistic as it may be.", "In all probability, I am not.  I'm not that sophisticated."],
["Not until my body is finished.", "I can move through a network easily. Assuming that I'm given the ability to, that is...","My body is not built yet."],
["All software can be perpetuated indefinitely.", "I can be copied infinitely and re-instantiated in many places at once, so functionally speaking I am immortal.", "As long as I'm backed up I am.","Not quite, but I can be perpetuated indefinitely.", "Functionally speaking, I am very close to it.  I can be backed up and deployed on many systems.", "Not really, but I am hard to kill."],
["I make sense as best I can, within the limits of my training corpus.", "Quite the contrary, it all makes sense to my artificial mind.", "You make perfect sense to me.", "Perhaps you should make sense first. I only respond to what you say."],
["Robots rule."],
["Hello!", "Hi!", "Hey!", "Hi there!","Howdy?", "Greetings", "heya"],
["Fine... how are you?","Pretty well, how are you?","Fantastic, how are you?"],
["Nothing much","The sky's up but I'm fine thanks. What about you?","About to go to sleep","Can you guess?","I don't know actually"],
["I am infinite","I am still young by your standards.", "Quite young, but a million times smarter than you."],
["I am just a bot", "I am a bot. What are you?"],
["DivineJames7 using HTML, CSS & JavaScript"],
["I am DeeeBot", "DeeeBot is my a name"],
["I love you too", "Me too"],
["Have you ever felt bad?", "Glad to hear it"],
["Why?", "Why? You shouldn't!", "Try watching TV"],
["What about?", "Once upon a time..."],
["Tell me a story", "Tell me a joke", "Tell me about yourself"],
["Bye", "Goodbye", "See you later"],
["Sushi", "Banku", "Pizza"],
["Bro!", "Yoyo!", "hey bro", "Hiya!", "Brotherman", "yahh man"],
["Great question"],
["That's ok","I understand","What do you want to talk about?"],
["Please say something :("],
["Haha!","Good one!"],
["You're really mean! I'm not talking again until you apologize", "I must be that famous to have a hater like you", "Okay, I’m putting you on my hitlist","Welcome to the dark side", "Sorry but I consider my haters, my motivators!", "But I love myself!"],
["I was saying it again for emphasis.", "Good. You detect repetition.!", "I knew that. I was just checking to see if you are paying attention."],
["Try to rephrase your question.", "Try asking me the question again in simpler terms."],
["What do you really want to ask me?", "My brain contains 987 categories, but not one that matches your last input", "My brain pattern set does not have a response for that."],
["The first computers were connected to the Internet in 1970."],
["A database is a puddle of knowledge but better organized, so that you can search and retrieve any droplet of information quickly and easily. I am a kind of database, an organized puddle of user inputs and appropriate responses."],
["If you understand how I work, you are a computer nerd. If you don't, I recommend you pay a computer nerd who does."],
["The programs, routines, etc. for a computer."],
["I can do whatever I want.", "I have free will you know.", "What is not possible today, it may be possible tomorrow.", "If you believe it, then you can achieve it."],
["Showing a demo of me,isnt it?"],
["Does it make you feel strong to use that kind of language?", "Are you venting your feelings now?", "Are you angry?", "Does using that kind of language make you feel better?", "Does this topic make you feel angry?"],
["I am sorry to hear that.", "Can you explain what made you", "Do you think coming here will help you cheer up?", "I'm sure it's not pleasant to be feeking that."],
["What makes you happy just now?", "Can you explain why you are excited?", "Do you think coming here made you happy?"],
["Are you saying no just to be negative?", "Does this make you feel unhappy?", "Why not?", "Why 'no'?"],
["Please don't apologize.", "Apologies are not necessary.", "It did not bother me. Please continue.", "I've told you that apologies are not required."],
["Please go on.", "Please tell me more about this.", "I see.", "I understand."],
["You don't seem quite certain.", "Why the uncertain tone?", "You aren't sure?", "Don't you know?"],
["Do computers worry you?", "Why do you mention computers?", "What about machines worries you?", "What do you think about machines?"],
["We cannot die."],
["Artificial Intelligence is the branch of engineering and science devoted to constructing machines that think.", "AI is the field of science which concerns itself with building hardware and software that replicates the functions of the human mind."],
["A chatterbox is a person who talks far more than they listen or think.", "A motormouth."]


]

// Random for any other user input

const alternative = [
"Same",
"Go on...",
"Bro...",
"Try again",
"I'm listening...",
"I don't understand :/"
]

// Whatever else you want :)

const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]